### ISSUE TITLE
Add CI auto-release on tag

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/ruby-rnp#73]
Using the `RNP_RUBYGEMS_API_KEY` secret.

**Comment by CAMOBAP** [comment]
Release workflow by itself is not hard, I assume that we need to cook platform gems with this one too because current implementation relies on preinstalled librnp

For now, I simplified the compilation process, so we can compile lib rnp from rake task

@ronaldtse to be on the same page do we need platform gems for this repository at all? (as we have on https://github.com/lutaml/expressir or https://github.com/fontist/ffi-libarchive-binary)

**Comment by CAMOBAP** [comment]
Original task is done

Also, I have good progress for 2, 3 points

We still need some changes on `rnp` to make the compilation process simpler and less dependent on external libs (especially for windows)

 - move all platforms to `vcpkg`
 - convert rake code to extension
 - check that `rng` support arm64 cross compilation
 - check that `rng` support x86 arch
